# Generated by Django 3.1 on 2020-08-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='brand',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
