# Generated by Django 3.1 on 2020-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0002_saleitems_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='brand',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
