# Generated by Django 3.1 on 2020-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0003_auto_20200827_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
