# Generated by Django 3.1 on 2020-08-27 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0004_saleitems_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
